server:
  port: 8081
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 5
  serviceUrl:
    defaultZone: http://eureka-svc:8761
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cooperatool2.mysql.database.azure.com:3306/calendar_test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false
    username: huijun@cooperatool2
    password: Wjswhdtjf764
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create
