server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 644db2020!
    url: jdbc:mysql://db-644.cria4byvgcl8.ap-northeast-2.rds.amazonaws.com:3306/db-644?serverTimezone=UTC
    username: admin
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true