server:
  port: 8100
  servlet:
    session:
      timeout: 30s
  thymeleaf:
    cache: false
    check-template-location: true
    mode: HTML5
    order: 0
    prefix: classpath:templates/
    suffix: .html
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka