server:
  port: 8500
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 5
  serviceUrl:
    defaultZone: http://localhost:8761
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db644.c1p3uode6sio.ap-northeast-2.rds.amazonaws.com:3306/db644?serverTimezone=UTC
    password: 644db2020!
    username: admin
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
